#include <plant_compat.h>

/*__PLANT_TYPES_BEGIN__*/
#ifndef PLANT_TYPES_INCLUDED
#define PLANT_TYPES_INCLUDED
#endif
/*__PLANT_TYPES_END__*/

tx_t main();


tx_t main() {
  tx_t u1 = "";
  tx_t u2 = "";
  tx_t u3 = "";
  tx_t u4 = "";
  tx_t l1 = "";
  tx_t l2 = "";
  tx_t l3 = "";
  tx_t t1 = "";
  tx_t t2 = "";
  tx_t t3 = "";
  tx_t t4 = "";
  tx_t t5 = "";
  tx_t t6 = "";
  tx_t i1 = "";
  tx_t i2 = "";
  tx_t i3 = "";
  tx_t i4 = "";
  tx_t i5 = "";
  tx_t s1 = "";
  tx_t s2 = "";
  tx_t s3 = "";
  tx_t s4 = "";
  tx_t e1 = "";
  tx_t e2 = "";
  tx_t e3 = "";
  tx_t e4 = "";
  tx_t r1 = "";
  tx_t r2 = "";
  tx_t r3 = "";
  tx_t r4 = "";
  tx_t r5 = "";
  tx_t x1 = "";
  tx_t x2 = "";
  tx_t x3 = "";
  tx_t x4 = "";
  tx_t x5 = "";
  tx_t p1 = "";
  tx_t p2 = "";
  tx_t p3 = "";
  tx_t p4 = "";
  tx_t q1 = "";
  tx_t q2 = "";
  tx_t q3 = "";
    plant_iReport_print(get_report(), "== upper ==");
    u1 = strings_UPPER("hello world");
    plant_iReport_print(get_report(), u1);
    u2 = strings_UPPER("Hello123!");
    plant_iReport_print(get_report(), u2);
    u3 = strings_UPPER("");
    plant_iReport_print(get_report(), _cat3("[", u3, "]"));
    u4 = strings_UPPER("X");
    plant_iReport_print(get_report(), u4);
    plant_iReport_print(get_report(), "== lower ==");
    l1 = strings_LOWER("HELLO WORLD");
    plant_iReport_print(get_report(), l1);
    l2 = strings_LOWER("MiXeD 42!");
    plant_iReport_print(get_report(), l2);
    l3 = strings_LOWER("");
    plant_iReport_print(get_report(), _cat3("[", l3, "]"));
    plant_iReport_print(get_report(), "== trim ==");
    t1 = strings_TRIM("  hi  ");
    plant_iReport_print(get_report(), _cat3("[", t1, "]"));
    t2 = strings_TRIM("no space");
    plant_iReport_print(get_report(), _cat3("[", t2, "]"));
    t3 = strings_TRIM("   ");
    plant_iReport_print(get_report(), _cat3("[", t3, "]"));
    t4 = strings_TRIM("");
    plant_iReport_print(get_report(), _cat3("[", t4, "]"));
    t5 = strings_TRIM("  lead");
    plant_iReport_print(get_report(), _cat3("[", t5, "]"));
    t6 = strings_TRIM("trail  ");
    plant_iReport_print(get_report(), _cat3("[", t6, "]"));
    plant_iReport_print(get_report(), "== includes ==");
    i1 = strings_INCLUDES("hello world", "lo wo");
    plant_iReport_print(get_report(), i1);
    i2 = strings_INCLUDES("hello", "xyz");
    plant_iReport_print(get_report(), i2);
    i3 = strings_INCLUDES("hello", "");
    plant_iReport_print(get_report(), i3);
    i4 = strings_INCLUDES("", "x");
    plant_iReport_print(get_report(), i4);
    i5 = strings_INCLUDES("a", "a");
    plant_iReport_print(get_report(), i5);
    plant_iReport_print(get_report(), "== starts_with ==");
    s1 = strings_STARTS_WITH("hello", "he");
    plant_iReport_print(get_report(), s1);
    s2 = strings_STARTS_WITH("hello", "lo");
    plant_iReport_print(get_report(), s2);
    s3 = strings_STARTS_WITH("hello", "");
    plant_iReport_print(get_report(), s3);
    s4 = strings_STARTS_WITH("", "h");
    plant_iReport_print(get_report(), s4);
    plant_iReport_print(get_report(), "== ends_with ==");
    e1 = strings_ENDS_WITH("hello", "llo");
    plant_iReport_print(get_report(), e1);
    e2 = strings_ENDS_WITH("hello", "hel");
    plant_iReport_print(get_report(), e2);
    e3 = strings_ENDS_WITH("hello", "");
    plant_iReport_print(get_report(), e3);
    e4 = strings_ENDS_WITH("", "o");
    plant_iReport_print(get_report(), e4);
    plant_iReport_print(get_report(), "== reverse ==");
    r1 = strings_REVERSE("abc");
    plant_iReport_print(get_report(), r1);
    r2 = strings_REVERSE("");
    plant_iReport_print(get_report(), _cat3("[", r2, "]"));
    r3 = strings_REVERSE("a");
    plant_iReport_print(get_report(), r3);
    r4 = strings_REVERSE("a b c");
    plant_iReport_print(get_report(), r4);
    r5 = strings_REVERSE("racecar");
    plant_iReport_print(get_report(), r5);
    plant_iReport_print(get_report(), "== repeat ==");
    x1 = strings_REPEAT("ab", 3);
    plant_iReport_print(get_report(), x1);
    x2 = strings_REPEAT("x", 0);
    plant_iReport_print(get_report(), _cat3("[", x2, "]"));
    x3 = strings_REPEAT("x", 1);
    plant_iReport_print(get_report(), x3);
    x4 = strings_REPEAT("", 5);
    plant_iReport_print(get_report(), _cat3("[", x4, "]"));
    x5 = strings_REPEAT("12", 4);
    plant_iReport_print(get_report(), x5);
    plant_iReport_print(get_report(), "== pad (right) ==");
    p1 = strings_PAD("x", 5, ".");
    plant_iReport_print(get_report(), p1);
    p2 = strings_PAD("hello", 3, ".");
    plant_iReport_print(get_report(), p2);
    p3 = strings_PAD("ab", 4, "-");
    plant_iReport_print(get_report(), p3);
    p4 = strings_PAD("ok", 2, ".");
    plant_iReport_print(get_report(), p4);
    plant_iReport_print(get_report(), "== pad_left ==");
    q1 = strings_PAD_LEFT("x", 5, ".");
    plant_iReport_print(get_report(), q1);
    q2 = strings_PAD_LEFT("hello", 3, ".");
    plant_iReport_print(get_report(), q2);
    q3 = strings_PAD_LEFT("ab", 4, "-");
    plant_iReport_print(get_report(), q3);
    plant_iReport_print(get_report(), "done");
    return 0;
}
